# Generated by Django 4.2.16 on 2026-08-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='driftDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='completedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
