# Generated by Django 4.2.16 on 2026-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
