# Generated by Django 4.2.16 on 2026-08-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0004_authotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleTask',
        ),
    ]
