# Generated by Django 4.2.16 on 2026-08-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0005_delete_scheduletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='areaAcres',
            field=models.FloatField(default=1.0),
        ),
    ]
