# Generated by Django 4.2.16 on 2026-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0007_farm_ec_farm_nitrogen_farm_organiccarbon_farm_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='riskRadarData',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
